//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCPArtNavi.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCPArtNavi.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Black Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_black_wool {
            get {
                return ResourceManager.GetString("ItemName_black_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_blue_wool {
            get {
                return ResourceManager.GetString("ItemName_blue_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brown Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_brown_wool {
            get {
                return ResourceManager.GetString("ItemName_brown_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyan Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_cyan_wool {
            get {
                return ResourceManager.GetString("ItemName_cyan_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gray Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_gray_wool {
            get {
                return ResourceManager.GetString("ItemName_gray_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_green_wool {
            get {
                return ResourceManager.GetString("ItemName_green_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Blue Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_light_blue_wool {
            get {
                return ResourceManager.GetString("ItemName_light_blue_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Gray Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_light_gray_wool {
            get {
                return ResourceManager.GetString("ItemName_light_gray_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lime Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_lime_wool {
            get {
                return ResourceManager.GetString("ItemName_lime_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magenta Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_magenta_wool {
            get {
                return ResourceManager.GetString("ItemName_magenta_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orange Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_orange_wool {
            get {
                return ResourceManager.GetString("ItemName_orange_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pink Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_pink_wool {
            get {
                return ResourceManager.GetString("ItemName_pink_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purple Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_purple_wool {
            get {
                return ResourceManager.GetString("ItemName_purple_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_red_wool {
            get {
                return ResourceManager.GetString("ItemName_red_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_Unknown {
            get {
                return ResourceManager.GetString("ItemName_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_white_wool {
            get {
                return ResourceManager.GetString("ItemName_white_wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yello Wool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemName_yellow_wool {
            get {
                return ResourceManager.GetString("ItemName_yellow_wool", resourceCulture);
            }
        }
    }
}
