//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCPArtNavi.UserApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCPArtNavi.UserApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   MC Pixel Art Navi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("ImportWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import(_I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Button_Import {
            get {
                return ResourceManager.GetString("ImportWindow_Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference(_R)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Button_Reference {
            get {
                return ResourceManager.GetString("ImportWindow_Button_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled items: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Label_EnabledItems {
            get {
                return ResourceManager.GetString("ImportWindow_Label_EnabledItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel Conversion uses Game Items that have been checked. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Label_EnabledItemsHint {
            get {
                return ResourceManager.GetString("ImportWindow_Label_EnabledItemsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import from: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Label_ImportFrom {
            get {
                return ResourceManager.GetString("ImportWindow_Label_ImportFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import size: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Label_ImportSize {
            get {
                return ResourceManager.GetString("ImportWindow_Label_ImportSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportWindow_Title {
            get {
                return ResourceManager.GetString("ImportWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document property(_R)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_DocumentProperty {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_DocumentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_Exit {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(_E)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_Export {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import(_I)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_Import {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New File(_N)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_NewFile {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_OpenFile {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_Save {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as(_A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_File_SaveAs {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_Help {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About MCPixcel Art Navi(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_Help_About {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit www.a32kita.net(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_Help_Website {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_Help_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_View {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show chunk(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_View_ShowChunk {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_View_ShowChunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show grid(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_View_ShowGrid {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_View_ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show tool panel(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_TopMenu_View_ShowToolPanel {
            get {
                return ResourceManager.GetString("MainWindow_TopMenu_View_ShowToolPanel", resourceCulture);
            }
        }
    }
}
